model:
  arch: UnetPlusPlus
  encoder_name: efficientnet-b3
  encoder_weights: imagenet

data:
  train_dir: ./train_images  # Location of DIV2K + BSD500 training images
  test_dir: ./test_images    # Location of images to be colorized
  crop:
    height: 320
    width: 320
  batch_size: 32
  num_workers: 8

training:
  num_epochs: 100
  learning_rate: 0.0025
  checkpoints_dir: ./checkpoints  # Directory for saving model checkpoints
  progress_dir: ./progress  # Directory for saving training progress images

testing:
  output_dir: ./colorized_outputs  # Directory for saving colorized test images